JuliaMolSim/Molly.jl

REQUIRE
src/Molly.jl
src/setup.jl

Replacing by the Normal distribution function in Distributions.jl for performance and accuracy improvement.

Fix Maxwell-Boltzmann Velocity function

---

src/forces.jl
src/types.jl

Hi!
I noticed that there some performance improvements that can be made. For example due to `atoms::Vector{<:Any}` a lot of dynamic dispatch was occurring inside force calculations. Adding another type parameter solved the problem and provided a ~40x speedup for Lenard-Jones interactions. I think further improvements can be made.

Performance improvements

---

src/forces.jl

I also added `return nothing` for the functions without branches for consistency.

return nothing for type stability

---

.gitignore

Since the Manifest is not checked in, it would be easier to add it to .gitignore to avoid accidentally adding it.

Ignore Manifest.toml

---

docs/src/docs.md
src/forces.jl

Very straightforward, a large constant is stored on the Mie struct to save on computation

add Mie Potential

---

src/spatial.jl

The `adjust_bounds` is optimized into a one-line using the `floor` in base julia.
Here is the simple benchmark.
benchamarked julia version : 1.6.1
```julia
julia> @time adjust_bounds(90001.0,3.0)
0.000029 seconds
1.0
julia> @time adjust_bounds_new(90001.0,3.0) # this is the function proposed
0.000000 seconds
1.0
```

Update adjust_bounds by removing iteration

---

docs/src/docs.md
src/cutoffs.jl
src/interactions/coulomb.jl
src/interactions/lennard_jones.jl
src/interactions/mie.jl
src/interactions/soft_sphere.jl
test/simulation.jl

This is a suggestion to add a spline cutoff, which interpolates between the true potential at a set activation distance and zero at a cutoff distance. The interpolation itself is based on a [cubic Hermite spline](https://en.wikipedia.org/wiki/Cubic_Hermite_spline).
The main addition consists in a new cutoff type, `CubicSplineCutoff` :
```
struct CubicSplineCutoff{D,S,I}
dist_cutoff::D
sqdist_cutoff::S
inv_sqdist_cutoff::I
dist_activation::D
sqdist_activation::S
inv_sqdist_activation::I
end
```
This cutoff comes with two methods 
`force_divr_cutoff(cutoff::CubicSplineCutoff, r2, inter, params)`
`potential_cutoff(cutoff::CubicSplineCutoff, r2, inter, params)`
which define the behaviour of the cutoff within the cutoff region, between `dist_activation` and `dist_cutoff` 
The naming convention …

Implement cubic spline cutoff

---

docs/src/examples.md

When deleting and adding a bond between atom `i` and `j`, the previous actions:
```Julia
delete!(atom_i.partners, atom_j.i)
delete!(atom_j.partners, atom_j.i)
```
and
```Julia
push!(atom_i.partners, atom_j.i)
push!(atom_j.partners, atom_j.i)
```
would get atom `i`'s partners correctly, but only delete/add itself from atom `j`'s partners. Instead, we should change as below:
```Julia
delete!(atom_i.partners, atom_j.i)
delete!(atom_j.partners, atom_i.i)
```
and
```Julia
push!(atom_i.partners, atom_j.i)
push!(atom_j.partners, atom_i.i)
```

Update atom i&j partners correctly

---

Project.toml
docs/src/docs.md
src/Molly.jl
src/loggers.jl
test/simulation.jl

This PR adds an `AverageObservableLogger` which keeps a running average of some observation, while maintaining an estimation of the standard deviation on this average. 
As an example, the following code 
```julia
using Molly
n_atoms = 1000
atom_mass = 10.0u"u"
atoms = [Atom(mass = atom_mass, σ = 0.2u"nm", ϵ = 0.2u"kJ * mol^-1") for i=1:n_atoms]
box_size = SVector(6.0, 6.0, 6.0)u"nm"
coords = place_diatomics(n_atoms ÷ 2, box_size, 0.2u"nm", 0.2u"nm")
temp = 50.0u"K"
velocities = [velocity(atom_mass, temp)*0.01 for i=1:n_atoms]
pairwise_inters = (SoftSphere(nl_only=true, cutoff=DistanceCutoff(0.6u"nm")),)
bonds = [HarmonicBond(b0=0.2u"nm", kb=10000u"kJ * mol^-1 * nm^-2") for i=1:(n_atoms ÷ 2)]
specific_inter_lists = (InteractionList2Atoms(collect(1:2:n_atoms), collect(2:2:n_atoms), …
```

Block averages

---

src/force.jl
src/interactions/gravity.jl

Several GPU kernels are not functional because of an `unsupported dynamic function call to force(...)`. This adds a simple fallback for calling `force(..., weight_14)` as just `force(...)`. It seems to work on my GPU, at least.

adding overload so GPU kernels execute without unsupported dynamic function call

---

src/interactions/cosine_angle.jl

found a typo in `cosine_angle.jl`, being corrected here.

correct a typo

---

docs/src/docs.md
src/interactions/coulomb.jl
src/interactions/lennard_jones.jl
test/interactions.jl

This PR adds soft core version of the Lennard jones and Coulomb pairwise interactions following the expressions in [Beutler, T. C.; Mark, A. E.; van Schaik, R. C.; Gerber, P. R.; van Gunsteren, W. F. Chem. Phys. Lett. 1994, 222, 529−539](https://doi.org/10.1016/0009-2614(94)00397-1).

Add `LennardJonesSoftCore` and `CoulombSoftCore`

---

src/interactions/coulomb.jl
src/interactions/lennard_jones.jl

Escaping not required as using `@doc raw`.

Fix inline math for docstring

---

src/interactions/coulomb.jl
src/interactions/lennard_jones.jl
src/interactions/mie.jl

Initial implementation of `LennardJonesSoftCore` and `CoulombSoftCore` was quite slow (several microseconds for single force calculation). This PR add a speed up to make it useable (now the times are about 150ns per force calculation, 3x slower than non-softcore interactions but still way better than before).
Also fixes #94 .

Speed up for softcore potentials and fixes to Mie

---

src/zygote.jl

Using the new extension system, it seems the `dualize` function defined in `FordwardDiff`'s `ForwardDiffStaticArraysExt` extension module is not importable (at least I could not manage to do it).
However, since the signature defined here (in Molly) is only used from within Zygote, I supposed it's safe to simply define it independent of `ForwardDiff`'s `dualize`. 
Maybe this `dualize` could/should be called `offset_dualize` to clearly distinguish it?
Using this little trick allowed me to load Molly on 1.9.0rc1.
However, I couldn't run `Pkg.test` because it fails due to some GL stuff not working (running it on a remote node without even an display server) and I was not using the differentiable capabilities so far, so I cannot say anything about correctness.

Hotfix for Julia 1.9

---

src/spatial.jl
test/basic.jl

I added checks for side length to be greater than zero for `CubicBoundary` and `RectangularBoundary`.
I did two unit tests locally. One of them gave an error shown below. Looks like zygote might create a `CubicBoundary` with negative side length. However, I was not able to reproduce this again. 
```
Gradients: Error During Test at /Users/yushengzhao/projects/Molly.jl/test/zygote.jl:1
Got exception outside of a @test
AssertionError: Side lengths need to be larger than 0
Stacktrace:
[1] CubicBoundary
@ ~/projects/Molly.jl/src/spatial.jl:38 [inlined]
[2] accum(x::NamedTuple{(:side_lengths,), Tuple{SizedVector{3, Float64, Vector{Float64}}}}, y::SVector{3, Float64})
@ Molly ~/projects/Molly.jl/src/zygote.jl:137
[3] (::Zygote.var"#back#291"{:contents, Zygote.Context{false}, Core.Box, …
```

Add Side Length checker

---

index.html

Fix default link for GitHub pages on the Molly github page.

Fix GitHub Pages Link

---

src/simulators.jl
test/simulation.jl

Thoughts on adding `run_loggers` parameter to all Simulator structs? I noticed it exists in the `StepestDescentMinimizer` but not other things like `VelocityVerlet`.
I ran into a use case where I would like to disable logging for the first 300k steps of a VV scheme and then re-enable it after the system has come to the correct temperature. Could also be worth allowing users to change what gets logged in-between calls to `simulate!` within the same code (maybe you can do this already I dunno). Something like `modify_loggers!(sys, ...)`. I also think there's a lot of performance to be gained here, maybe by writing to a file instead of RAM, just a thought.
I have not gone thru and made all the necessary changes just wanted to open this to discussion.

Add option to disable loggers in all Simulator structs

---

src/simulators.jl

The code I wrote for this integrator is limited to ergodic systems as pointed out this paper:
https://www2.stat.duke.edu/~scs/Projects/REMD/NoseHooverChains1992.pdf
I will update this code at some point to use a new integration scheme as outlined in the paper below. This might be a bit beyond my capabilities in terms of math, but this is the default scheme in LAMMPS for NVT and NPT:
https://iopscience.iop.org/article/10.1088/0305-4470/39/19/S18/pdf

Add caveat to NoseHoover docs

---

src/coupling.jl
src/spatial.jl
test/simulation.jl

This PR adds an implementation for the anisotropic Monte Carlo barostat following OpenMM's implementation.
The new interface for using this barostat in 3D and 2D systems is:
```julia
MonteCarloAnisotropicBarostat(
1.0u"bar", # Pressure in the X-axis
1.0u"bar", # Pressure in the Y-axis
1.0u"bar", # Pressure in the Z-axis
temperature,
boundary
)
```
and
```julia
MonteCarloAnisotropicBarostat(
1.0u"bar*nm", # Pressure in the X-axis
1.0u"bar*nm", # Pressure in the Y-axis
temperature,
boundary
)
```
respectively.
If you set any pressure value as 'nothing', the barostat is uncoupled in that axis. For example, for coupling only the Y-axis, you could do the following:
```julia
MonteCarloAnisotropicBarostat(
nothing, # Keep the box in the X-axis fixed
1.0u"bar", # Scale box in the Y-axis
nothing, …
```

Add anisotropic MC barostat

---

src/coupling.jl

The MC barostat adjusts the scaling in each axis depending on the trials. In the case of the membrane barostat, when the X and Y axes are coupled isotropically, the scaling adjustment should be performed in both axes. An alternative approach is to always select the X-axis when scaling in the XY plane (as OpenMM does). This PR implements that approach:
```julia
axis = barostat.xy_isotropy && axis == 2 ? 1 : axis
```

fix MC membrane barostat scaling factor adjustment

---

src/types.jl
src/units.jl

AtomsBase does not define what types to use for position and velocity. This can cause some problems, e.g., ExtXYZ data format causes these. To fix this, you need to convert to defined data structure (`SVector` here).
Also, some checks to coordinates and velocities caused some errors. So, I updated those as well.
There are still some potential issues, like what to do, if velocities are missing. I can add a fix for this too, or do you want to do that in some other PR?

Fix creation of Molly.System from AtomsBase structures

---

src/cuda.jl
src/energy.jl
src/force.jl
src/neighbors.jl
src/setup.jl
src/simulators.jl
test/basic.jl
test/energy_conservation.jl
test/protein.jl
test/simulation.jl

This PR introduces a GPU-optimized algorithm for the calculation of nonbonded forces. The algorithm subdivides the system into blocks of 32 particles, evaluates distances between blocks, and computes forces only for interacting blocks within a cutoff radius. The algorithm is incorporated into OpenMM and it is described in a paper by Eastman and Pande (https://onlinelibrary.wiley.com/doi/full/10.1002/jcc.21413).
This new implementation significantly accelerates nonbonded force calculations for large systems as its performance scales linearly with the number of atoms. 
- The algorithm divides the N atoms in bounding boxes of 32. A bounding box is the smallest rectangular, axis-aligned  box that contains 32 atoms. The identification of these boxes is a O(N) problem. 
- For reasons of spatial …

Nonbonded kernel
